PASTEL_RED = "#FFD0D3"
PASTEL_YELLOW = "#FFF1C7"
PASTEL_GREEN = "#CDF8CC"
PASTEL_BLUE = "#CDF2FE"
PASTEL_PURPLE = "#c3a0de"
PURPLE= "#c3a0de"
PASTEL_DARK_PURPLE = "#473D53"

APP_BACKGROUND = "#FBFAF8"
SURFACE = "#FFFFFF"
SURFACE_MUTED = "#F3FAFE"
TEXT_PRIMARY = "#313442"
TEXT_SECONDARY = "#6B7280"
BORDER = "#E7EBF3"


CONFIRM = PASTEL_GREEN
CANCEL = PASTEL_RED
WARNING = PASTEL_YELLOW
PRIMARY_SOFT = PASTEL_BLUE
SECONDARY_SOFT = PASTEL_PURPLE
INPUT_SHELL_HOVER_BG = "#F5F5F5"